### PR TITLE
CSS: Create/Update Poll Version 1

### PR DESCRIPTION
**Pull request by jduong09**

### CODE REVIEW

**Review by ziggysauce — COMMENTED** [review]
one observation: instead of the red color you're using, might i suggest a different color that doesn't represent a "negative" color. to me, seeing the blocks of red more so implies times of unavailability.

---

when hovering over time slots, the 12 hr range shows `00:15` etc, but i think you should just show `12:15` etc since you're showing the times in 12hr format and not 24hr format


Screen Shot 2023-12-09 at 9 47 56 AM
Screen Shot 2023-12-09 at 9 47 48 AM

**Comment by jduong09** [comment]
I see what you mean, I'll look for a different base color. Thanks for the suggestion

**Review by ziggysauce — CHANGES_REQUESTED** [review]
hot damn, the most recent update looks SO much better! nice job. just some minor feedback, otherwise i think this branch is good to go

---

when adding responses to a poll, this space can better be utilized on desktop i think. the entire right side is empty white space where more of the selection boxes could fit

Screen Shot 2024-01-01 at 1 58 03 PM

---

After submitting a response, I get redirected to the root `/` route which right now shows all polls, but i think we said that was just for testing, and instead it'll just take them to the homepage. I think another option we can consider if having the redirect take them to a "viewable" state of the poll maybe? Basically the "admin" view but without access to "edit" or "delete" the poll, just let them see the responses. (this isn't UI specific so can be tackled in a different branch)

---

When submitting a response, I think the name input should actually be at the top of the form instead of the bottom. Or if you prefer it at the bottom, I would just make that name and submit UI sticky to the bottom so it's always visible perhaps.

--- 

For the date UI, instead of YYYY-MM-DD I think it'd be simpler to view it as M/D/YY. Would also give each card more breathing room. Right now, with too much text it feels crowded.

Screen Shot 2024-01-01 at 2 03 33 PM

**Comment by ziggysauce** [comment]
^^ alright some of these comments are addressed in your other branch PRs. So we can probs merge some of those in to consolidate imo

**Comment by jduong09** [comment]
## Update
- Added star indicator to ALL dates that had the most responses, even if the most responses is shared between many dates.

**Comment by jduong09** [comment]
## Update
- Made some final margin changes for this PR. 
- Added SVGs for description, location in the Response Form.


Merging PR into main, closing PR.

**Pull request merged**
