### PR TITLE
Landing Page

### PR DESCRIPTION
**Pull request by jduong09**
### Feature
- Mobile and Desktop Design for Landing Page.
- Finalized CSS for Landing Page.

### CODE REVIEW

**Comment by jduong09** [comment]
### Update
- This PR is ready to have some preliminary review.
- I think i'll make changes to include desktop view images for when the user's viewport is in desktop view.
- I will need to take a look at some different devices.

**Review by ziggysauce — CHANGES_REQUESTED** [review]
overall looks great! i would add a tiny bit more padding/margin around the text and "Get Started" button. But otherwise, just a few comments and i think it's fine:

these buttons should be lined up

Screen Shot 2024-01-23 at 4 22 16 PM

---

something funky is going on with the images when in mobile

https://github.com/jduong09/doodle/assets/25065329/3baacfbb-49b4-45d4-98c3-956c4fb91595

^^ furthermore, that hero image you're using probably doesn't need to be so big when on mobile. it takes up too much real estate imo and detracts the user from the actual purpose of the page

**Comment by jduong09** [comment]
## Update
- Reduced size of hero image, made images look better at their respective view width.
- Fixed logic on carousel, should be working as intended.
- Issue with two buttons on admin view can be forgotten, it's changed in a different PR.

**Comment by jduong09** [comment]
##Update
- Merged changes from updated main branch.
- Finished PR.

**Pull request merged**
